proxy:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/nginx_config:/etc/nginx
    - ${NFS_HOST}/nfs/nginx_releasenote:/usr/share/nginx/html

ldap:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/ldap_db:/var/lib/ldap
    - ${NFS_HOST}/nfs/ldap_static:/etc/ldap

gerrit-mysql:
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/gerrit_mysql_data:/var/lib/mysql

gerrit:
  user: root
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/git_repos:/var/git/repos 
    - ${NFS_HOST}/nfs/gerrit_review_site:/var/gerrit/review_site 

jenkins:
  user: root 
  volume_driver: nfs
  volumes:
    - ${NFS_HOST}/nfs/jenkins_home:/var/jenkins_home 