proxy:
  volumes:
    - nginx_config:/etc/nginx
    - nginx_releasenote:/usr/share/nginx/html

ldap:
  volumes:
      - ldap_db:/var/lib/ldap
      - ldap_static:/etc/ldap

gerrit-mysql:
  volumes:
    - gerrit_mysql_data:/var/lib/mysql

gerrit:
  user: root
  volumes:
    - git_repos:/var/git/repos 
    - gerrit_review_site:/var/gerrit/review_site 


jenkins-slave:
  volumes:
    - jenkins_slave_home:/workspace
    - /var/run/docker.sock:/var/run/docker.sock

jenkins:
  user: root 
  volumes:
    - jenkins_home:/var/jenkins_home 
    - /var/run/docker.sock:/var/run/docker.sock